// GENERATED by tools/a2/gen_schema.py from synthyy registry.rs. Do not edit.
#pragma once
#include "core/Device.h"

namespace ddaw::schema {

inline constexpr ParamSpec kInstPoly[] = {
    {0, "wave", 0.0f, 6.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {1, "spread", 0.0f, 60.0f, 18.0f, Curve::Linear, 15.0f, false},
    {2, "cutoff", 80.0f, 14000.0f, 7000.0f, Curve::Exponential, 15.0f, false},
    {3, "res", 0.0f, 10.0f, 0.7f, Curve::Linear, 15.0f, false},
    {4, "slope", 0.0f, 2.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {5, "attack", 0.001f, 2.0f, 0.01f, Curve::Exponential, 15.0f, false},
    {6, "decay", 0.01f, 2.0f, 0.15f, Curve::Exponential, 15.0f, false},
    {7, "sustain", 0.0f, 1.0f, 0.6f, Curve::Linear, 15.0f, false},
    {8, "release", 0.01f, 4.0f, 0.4f, Curve::Exponential, 15.0f, false},
    {9, "lfoShape", 0.0f, 3.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {10, "lfoRate", 0.05f, 16.0f, 2.0f, Curve::Exponential, 15.0f, false},
    {11, "lfoAmt", 0.0f, 1.0f, 0.0f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kInstDuo[] = {
    {0, "harm", 0.5f, 3.0f, 1.5f, Curve::Linear, 15.0f, false},
    {1, "vibAmt", 0.0f, 0.6f, 0.12f, Curve::Linear, 15.0f, false},
    {2, "vibRate", 0.5f, 10.0f, 4.5f, Curve::Exponential, 15.0f, false},
    {3, "attack", 0.001f, 2.0f, 0.02f, Curve::Exponential, 15.0f, false},
    {4, "decay", 0.01f, 2.0f, 0.3f, Curve::Exponential, 15.0f, false},
    {5, "sustain", 0.0f, 1.0f, 0.6f, Curve::Linear, 15.0f, false},
    {6, "release", 0.01f, 4.0f, 0.6f, Curve::Exponential, 15.0f, false},
};

inline constexpr ParamSpec kInstFm[] = {
    {0, "harm", 0.25f, 8.0f, 3.0f, Curve::Linear, 15.0f, false},
    {1, "modIdx", 0.5f, 40.0f, 10.0f, Curve::Exponential, 15.0f, false},
    {2, "attack", 0.001f, 2.0f, 0.005f, Curve::Exponential, 15.0f, false},
    {3, "decay", 0.01f, 2.0f, 0.3f, Curve::Exponential, 15.0f, false},
    {4, "sustain", 0.0f, 1.0f, 0.4f, Curve::Linear, 15.0f, false},
    {5, "release", 0.01f, 4.0f, 0.6f, Curve::Exponential, 15.0f, false},
};

inline constexpr ParamSpec kInstMono[] = {
    {0, "wave", 0.0f, 3.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {1, "cutoff", 40.0f, 8000.0f, 900.0f, Curve::Exponential, 15.0f, false},
    {2, "res", 0.0f, 10.0f, 2.0f, Curve::Linear, 15.0f, false},
    {3, "slope", 0.0f, 2.0f, 1.0f, Curve::Stepped, 0.0f, false},
    {4, "envAmt", 0.0f, 6.0f, 2.5f, Curve::Linear, 15.0f, false},
    {5, "glide", 0.0f, 0.3f, 0.02f, Curve::Linear, 15.0f, false},
    {6, "attack", 0.001f, 2.0f, 0.003f, Curve::Exponential, 15.0f, false},
    {7, "decay", 0.01f, 2.0f, 0.2f, Curve::Exponential, 15.0f, false},
    {8, "sustain", 0.0f, 1.0f, 0.45f, Curve::Linear, 15.0f, false},
    {9, "release", 0.01f, 4.0f, 0.25f, Curve::Exponential, 15.0f, false},
    {10, "lfoShape", 0.0f, 3.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {11, "lfoRate", 0.05f, 16.0f, 2.0f, Curve::Exponential, 15.0f, false},
    {12, "lfoAmt", 0.0f, 1.0f, 0.0f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kInstPluck[] = {
    {0, "dampen", 500.0f, 12000.0f, 4000.0f, Curve::Exponential, 15.0f, false},
    {1, "res", 0.3f, 0.98f, 0.93f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kInstKeys[] = {
    {0, "harm", 0.5f, 4.0f, 2.0f, Curve::Linear, 15.0f, false},
    {1, "attack", 0.001f, 2.0f, 0.01f, Curve::Exponential, 15.0f, false},
    {2, "decay", 0.01f, 2.0f, 0.4f, Curve::Exponential, 15.0f, false},
    {3, "sustain", 0.0f, 1.0f, 0.5f, Curve::Linear, 15.0f, false},
    {4, "release", 0.01f, 4.0f, 0.8f, Curve::Exponential, 15.0f, false},
};

inline constexpr ParamSpec kInstSampler[] = {
    {0, "tune", -24.0f, 24.0f, 0.0f, Curve::Linear, 15.0f, false},
    {1, "attack", 0.001f, 1.0f, 0.005f, Curve::Exponential, 15.0f, false},
    {2, "release", 0.01f, 3.0f, 0.4f, Curve::Exponential, 15.0f, false},
};

inline constexpr ParamSpec kInstKsampler[] = {
    {0, "root", 0.0f, 11.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {1, "tune", -24.0f, 24.0f, 0.0f, Curve::Linear, 15.0f, false},
    {2, "attack", 0.001f, 2.0f, 0.004f, Curve::Exponential, 15.0f, false},
    {3, "release", 0.01f, 4.0f, 0.4f, Curve::Exponential, 15.0f, false},
};

inline constexpr ParamSpec kInstGranular[] = {
    {0, "size", 0.02f, 0.5f, 0.12f, Curve::Exponential, 15.0f, false},
    {1, "dens", 2.0f, 80.0f, 18.0f, Curve::Exponential, 15.0f, false},
    {2, "pos", 0.0f, 1.0f, 0.15f, Curve::Linear, 15.0f, false},
    {3, "spray", 0.0f, 1.0f, 0.05f, Curve::Linear, 15.0f, false},
    {4, "pitch", -24.0f, 24.0f, 0.0f, Curve::Linear, 15.0f, false},
    {5, "pjit", 0.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
    {6, "rev", 0.0f, 1.0f, 0.0f, Curve::Linear, 15.0f, false},
    {7, "shape", 0.0f, 1.0f, 0.5f, Curve::Linear, 15.0f, false},
    {8, "spread", 0.0f, 1.0f, 0.6f, Curve::Linear, 15.0f, false},
    {9, "attack", 0.001f, 2.0f, 0.05f, Curve::Exponential, 15.0f, false},
    {10, "release", 0.01f, 4.0f, 0.4f, Curve::Exponential, 15.0f, false},
};

inline constexpr ParamSpec kInstDrum[] = {
    {0, "p0_tune", -12.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
    {1, "p0_decay", 0.03f, 2.0f, 0.42f, Curve::Exponential, 15.0f, false},
    {2, "p0_level", -24.0f, 6.0f, 0.0f, Curve::Linear, 15.0f, false},
    {3, "p1_tune", -12.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
    {4, "p1_decay", 0.03f, 2.0f, 0.18f, Curve::Exponential, 15.0f, false},
    {5, "p1_level", -24.0f, 6.0f, 0.0f, Curve::Linear, 15.0f, false},
    {6, "p2_tune", -12.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
    {7, "p2_decay", 0.03f, 2.0f, 0.28f, Curve::Exponential, 15.0f, false},
    {8, "p2_level", -24.0f, 6.0f, 0.0f, Curve::Linear, 15.0f, false},
    {9, "p3_tune", -12.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
    {10, "p3_decay", 0.03f, 2.0f, 0.06f, Curve::Exponential, 15.0f, false},
    {11, "p3_level", -24.0f, 6.0f, 0.0f, Curve::Linear, 15.0f, false},
    {12, "p4_tune", -12.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
    {13, "p4_decay", 0.03f, 2.0f, 0.4f, Curve::Exponential, 15.0f, false},
    {14, "p4_level", -24.0f, 6.0f, 0.0f, Curve::Linear, 15.0f, false},
    {15, "p5_tune", -12.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
    {16, "p5_decay", 0.03f, 2.0f, 0.32f, Curve::Exponential, 15.0f, false},
    {17, "p5_level", -24.0f, 6.0f, 0.0f, Curve::Linear, 15.0f, false},
    {18, "p6_tune", -12.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
    {19, "p6_decay", 0.03f, 2.0f, 0.12f, Curve::Exponential, 15.0f, false},
    {20, "p6_level", -24.0f, 6.0f, 0.0f, Curve::Linear, 15.0f, false},
    {21, "p7_tune", -12.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
    {22, "p7_decay", 0.03f, 2.0f, 1.3f, Curve::Exponential, 15.0f, false},
    {23, "p7_level", -24.0f, 6.0f, 0.0f, Curve::Linear, 15.0f, false},
};

inline constexpr std::span<const ParamSpec> kInstAudiobus{};  // no parameters

inline constexpr ParamSpec kFxEq[] = {
    {0, "low", -12.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
    {1, "mid", -12.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
    {2, "high", -12.0f, 12.0f, 0.0f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxFilter[] = {
    {0, "ftype", 0.0f, 2.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {1, "freq", 40.0f, 18000.0f, 2000.0f, Curve::Exponential, 15.0f, false},
    {2, "q", 0.0f, 12.0f, 1.0f, Curve::Linear, 15.0f, false},
    {3, "slope", 0.0f, 2.0f, 0.0f, Curve::Stepped, 0.0f, false},
};

inline constexpr ParamSpec kFxDelay[] = {
    {0, "time", 0.0f, 5.0f, 2.0f, Curve::Stepped, 0.0f, false},
    {1, "fb", 0.0f, 0.85f, 0.35f, Curve::Linear, 15.0f, false},
    {2, "mix", 0.0f, 1.0f, 0.35f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxReverb[] = {
    {0, "size", 0.2f, 10.0f, 2.2f, Curve::Exponential, 15.0f, false},
    {1, "mix", 0.0f, 1.0f, 0.3f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxPlate[] = {
    {0, "decay", 0.3f, 8.0f, 1.8f, Curve::Exponential, 15.0f, false},
    {1, "predelay", 0.0f, 0.2f, 0.02f, Curve::Linear, 15.0f, false},
    {2, "damp", 500.0f, 16000.0f, 6000.0f, Curve::Exponential, 15.0f, false},
    {3, "mix", 0.0f, 1.0f, 0.3f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxEq7[] = {
    {0, "b0_freq", 20.0f, 20000.0f, 60.0f, Curve::Exponential, 15.0f, false},
    {1, "b0_gain", -15.0f, 15.0f, 0.0f, Curve::Linear, 15.0f, false},
    {2, "b0_q", 0.3f, 12.0f, 1.0f, Curve::Exponential, 15.0f, false},
    {3, "b1_freq", 20.0f, 20000.0f, 150.0f, Curve::Exponential, 15.0f, false},
    {4, "b1_gain", -15.0f, 15.0f, 0.0f, Curve::Linear, 15.0f, false},
    {5, "b1_q", 0.3f, 12.0f, 1.0f, Curve::Exponential, 15.0f, false},
    {6, "b2_freq", 20.0f, 20000.0f, 400.0f, Curve::Exponential, 15.0f, false},
    {7, "b2_gain", -15.0f, 15.0f, 0.0f, Curve::Linear, 15.0f, false},
    {8, "b2_q", 0.3f, 12.0f, 1.0f, Curve::Exponential, 15.0f, false},
    {9, "b3_freq", 20.0f, 20000.0f, 1000.0f, Curve::Exponential, 15.0f, false},
    {10, "b3_gain", -15.0f, 15.0f, 0.0f, Curve::Linear, 15.0f, false},
    {11, "b3_q", 0.3f, 12.0f, 1.0f, Curve::Exponential, 15.0f, false},
    {12, "b4_freq", 20.0f, 20000.0f, 2500.0f, Curve::Exponential, 15.0f, false},
    {13, "b4_gain", -15.0f, 15.0f, 0.0f, Curve::Linear, 15.0f, false},
    {14, "b4_q", 0.3f, 12.0f, 1.0f, Curve::Exponential, 15.0f, false},
    {15, "b5_freq", 20.0f, 20000.0f, 6000.0f, Curve::Exponential, 15.0f, false},
    {16, "b5_gain", -15.0f, 15.0f, 0.0f, Curve::Linear, 15.0f, false},
    {17, "b5_q", 0.3f, 12.0f, 1.0f, Curve::Exponential, 15.0f, false},
    {18, "b6_freq", 20.0f, 20000.0f, 12000.0f, Curve::Exponential, 15.0f, false},
    {19, "b6_gain", -15.0f, 15.0f, 0.0f, Curve::Linear, 15.0f, false},
    {20, "b6_q", 0.3f, 12.0f, 1.0f, Curve::Exponential, 15.0f, false},
};

inline constexpr ParamSpec kFxChorus[] = {
    {0, "rate", 0.01f, 300.0f, 1.5f, Curve::Exponential, 15.0f, false},  // rateSwitch: Sync/Low/High rate modes
    {1, "depth", 0.0f, 1.0f, 0.5f, Curve::Linear, 15.0f, false},
    {2, "mix", 0.0f, 1.0f, 0.5f, Curve::Linear, 15.0f, false},
    {3, "rateMode", 0.0f, 2.0f, 1.0f, Curve::Stepped, 0.0f, false},  // 0 Sync, 1 Low (rate), 2 High (rateHi)
    {4, "rateSync", 0.0f, 8.0f, 5.0f, Curve::Stepped, 0.0f, false},  // tempo division index
    {5, "rateHi", 301.0f, 1000.0f, 440.0f, Curve::Stepped, 0.0f, false},  // Hz, High mode
};

inline constexpr ParamSpec kFxDist[] = {
    {0, "amt", 0.0f, 1.0f, 0.4f, Curve::Linear, 15.0f, false},
    {1, "mix", 0.0f, 1.0f, 1.0f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxCrush[] = {
    {0, "bits", 1.0f, 16.0f, 8.0f, Curve::Stepped, 0.0f, false},
    {1, "mix", 0.0f, 1.0f, 1.0f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxComp[] = {
    {0, "thresh", -60.0f, 0.0f, -20.0f, Curve::Linear, 15.0f, false},
    {1, "ratio", 1.0f, 20.0f, 4.0f, Curve::Linear, 15.0f, false},
    {2, "attack", 0.001f, 0.3f, 0.01f, Curve::Exponential, 15.0f, false},
    {3, "release", 0.02f, 1.0f, 0.2f, Curve::Exponential, 15.0f, false},
};

inline constexpr ParamSpec kFxOpto[] = {
    {0, "reduction", 0.0f, 1.0f, 0.4f, Curve::Linear, 15.0f, false},
    {1, "gain", -12.0f, 24.0f, 0.0f, Curve::Linear, 15.0f, false},
    {2, "mode", 0.0f, 1.0f, 0.0f, Curve::Stepped, 0.0f, false},
};

inline constexpr ParamSpec kFxMbcomp[] = {
    {0, "mode", 0.0f, 1.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {1, "xlo", 60.0f, 1000.0f, 250.0f, Curve::Exponential, 15.0f, false},
    {2, "xhi", 1000.0f, 12000.0f, 2500.0f, Curve::Exponential, 15.0f, false},
    {3, "attack", 0.001f, 0.3f, 0.02f, Curve::Exponential, 15.0f, false},
    {4, "release", 0.02f, 1.0f, 0.18f, Curve::Exponential, 15.0f, false},
    {5, "b0_thresh", -60.0f, 0.0f, -24.0f, Curve::Linear, 15.0f, false},
    {6, "b0_ratio", 1.0f, 20.0f, 2.0f, Curve::Linear, 15.0f, false},
    {7, "b0_gain", -24.0f, 24.0f, 0.0f, Curve::Linear, 15.0f, false},
    {8, "b1_thresh", -60.0f, 0.0f, -24.0f, Curve::Linear, 15.0f, false},
    {9, "b1_ratio", 1.0f, 20.0f, 2.0f, Curve::Linear, 15.0f, false},
    {10, "b1_gain", -24.0f, 24.0f, 0.0f, Curve::Linear, 15.0f, false},
    {11, "b2_thresh", -60.0f, 0.0f, -24.0f, Curve::Linear, 15.0f, false},
    {12, "b2_ratio", 1.0f, 20.0f, 2.0f, Curve::Linear, 15.0f, false},
    {13, "b2_gain", -24.0f, 24.0f, 0.0f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxGate[] = {
    {0, "thresh", -80.0f, 0.0f, -40.0f, Curve::Linear, 15.0f, false},
    {1, "up", -40.0f, 40.0f, 0.0f, Curve::Linear, 15.0f, false},
    {2, "dn", -40.0f, 40.0f, -6.0f, Curve::Linear, 15.0f, false},
    {3, "range", -100.0f, 0.0f, -60.0f, Curve::Linear, 15.0f, false},
    {4, "ratio", 1.0f, 20.0f, 20.0f, Curve::Linear, 15.0f, false},
    {5, "knee", 0.0f, 24.0f, 3.0f, Curve::Linear, 15.0f, false},
    {6, "attack", 0.0001f, 0.3f, 0.002f, Curve::Exponential, 15.0f, false},
    {7, "hold", 0.001f, 2.0f, 0.05f, Curve::Exponential, 15.0f, false},
    {8, "release", 0.005f, 3.0f, 0.15f, Curve::Exponential, 15.0f, false},
    {9, "look", 0.0f, 10.0f, 0.0f, Curve::Linear, 15.0f, false},
    {10, "hpf", 20.0f, 2000.0f, 20.0f, Curve::Exponential, 15.0f, false},
    {11, "lpf", 200.0f, 20000.0f, 20000.0f, Curve::Exponential, 15.0f, false},
    {12, "key", 0.0f, 4.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {13, "det", 0.0f, 1.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {14, "listen", 0.0f, 1.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {15, "inverse", 0.0f, 1.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {16, "mix", 0.0f, 1.0f, 1.0f, Curve::Linear, 15.0f, false},
    {17, "gain", -24.0f, 24.0f, 0.0f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxPhaser[] = {
    {0, "rate", 0.01f, 300.0f, 0.8f, Curve::Exponential, 15.0f, false},  // rateSwitch: Sync/Low/High rate modes
    {1, "octaves", 1.0f, 6.0f, 3.0f, Curve::Stepped, 0.0f, false},
    {2, "mix", 0.0f, 1.0f, 0.5f, Curve::Linear, 15.0f, false},
    {3, "rateMode", 0.0f, 2.0f, 1.0f, Curve::Stepped, 0.0f, false},  // 0 Sync, 1 Low (rate), 2 High (rateHi)
    {4, "rateSync", 0.0f, 8.0f, 5.0f, Curve::Stepped, 0.0f, false},  // tempo division index
    {5, "rateHi", 301.0f, 1000.0f, 440.0f, Curve::Stepped, 0.0f, false},  // Hz, High mode
};

inline constexpr ParamSpec kFxPingpong[] = {
    {0, "time", 0.0f, 5.0f, 2.0f, Curve::Stepped, 0.0f, false},
    {1, "fb", 0.0f, 0.85f, 0.4f, Curve::Linear, 15.0f, false},
    {2, "mix", 0.0f, 1.0f, 0.3f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxAutofilt[] = {
    {0, "rate", 0.01f, 300.0f, 1.0f, Curve::Exponential, 15.0f, false},  // rateSwitch: Sync/Low/High rate modes
    {1, "depth", 0.0f, 1.0f, 0.7f, Curve::Linear, 15.0f, false},
    {2, "base", 80.0f, 4000.0f, 350.0f, Curve::Exponential, 15.0f, false},
    {3, "mix", 0.0f, 1.0f, 1.0f, Curve::Linear, 15.0f, false},
    {4, "rateMode", 0.0f, 2.0f, 1.0f, Curve::Stepped, 0.0f, false},  // 0 Sync, 1 Low (rate), 2 High (rateHi)
    {5, "rateSync", 0.0f, 8.0f, 5.0f, Curve::Stepped, 0.0f, false},  // tempo division index
    {6, "rateHi", 301.0f, 1000.0f, 440.0f, Curve::Stepped, 0.0f, false},  // Hz, High mode
};

inline constexpr ParamSpec kFxTrem[] = {
    {0, "rate", 0.01f, 300.0f, 5.0f, Curve::Exponential, 15.0f, false},  // rateSwitch: Sync/Low/High rate modes
    {1, "depth", 0.0f, 1.0f, 0.6f, Curve::Linear, 15.0f, false},
    {2, "mix", 0.0f, 1.0f, 1.0f, Curve::Linear, 15.0f, false},
    {3, "rateMode", 0.0f, 2.0f, 1.0f, Curve::Stepped, 0.0f, false},  // 0 Sync, 1 Low (rate), 2 High (rateHi)
    {4, "rateSync", 0.0f, 8.0f, 5.0f, Curve::Stepped, 0.0f, false},  // tempo division index
    {5, "rateHi", 301.0f, 1000.0f, 440.0f, Curve::Stepped, 0.0f, false},  // Hz, High mode
};

inline constexpr ParamSpec kFxAutopan[] = {
    {0, "rate", 0.01f, 300.0f, 1.5f, Curve::Exponential, 15.0f, false},  // rateSwitch: Sync/Low/High rate modes
    {1, "depth", 0.0f, 1.0f, 0.8f, Curve::Linear, 15.0f, false},
    {2, "rateMode", 0.0f, 2.0f, 1.0f, Curve::Stepped, 0.0f, false},  // 0 Sync, 1 Low (rate), 2 High (rateHi)
    {3, "rateSync", 0.0f, 8.0f, 5.0f, Curve::Stepped, 0.0f, false},  // tempo division index
    {4, "rateHi", 301.0f, 1000.0f, 440.0f, Curve::Stepped, 0.0f, false},  // Hz, High mode
};

inline constexpr ParamSpec kFxVib[] = {
    {0, "rate", 0.01f, 300.0f, 5.0f, Curve::Exponential, 15.0f, false},  // rateSwitch: Sync/Low/High rate modes
    {1, "depth", 0.0f, 0.6f, 0.15f, Curve::Linear, 15.0f, false},
    {2, "mix", 0.0f, 1.0f, 1.0f, Curve::Linear, 15.0f, false},
    {3, "rateMode", 0.0f, 2.0f, 1.0f, Curve::Stepped, 0.0f, false},  // 0 Sync, 1 Low (rate), 2 High (rateHi)
    {4, "rateSync", 0.0f, 8.0f, 5.0f, Curve::Stepped, 0.0f, false},  // tempo division index
    {5, "rateHi", 301.0f, 1000.0f, 440.0f, Curve::Stepped, 0.0f, false},  // Hz, High mode
};

inline constexpr ParamSpec kFxCheby[] = {
    {0, "order", 2.0f, 14.0f, 3.0f, Curve::Stepped, 0.0f, false},
    {1, "mix", 0.0f, 1.0f, 0.35f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxWiden[] = {
    {0, "width", 0.0f, 1.0f, 0.8f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxShift[] = {
    {0, "amt", -400.0f, 400.0f, 60.0f, Curve::Linear, 15.0f, false},
    {1, "mix", 0.0f, 1.0f, 0.4f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxDuck[] = {
    {0, "rate", 0.0f, 5.0f, 1.0f, Curve::Stepped, 0.0f, false},
    {1, "amount", 0.0f, 1.0f, 0.7f, Curve::Linear, 15.0f, false},
    {2, "curve", 0.1f, 1.0f, 0.5f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kFxAutotune[] = {
    {0, "amount", 0.0f, 1.0f, 1.0f, Curve::Linear, 15.0f, false},
    {1, "speed", 1.0f, 200.0f, 20.0f, Curve::Exponential, 15.0f, false},
    {2, "mix", 0.0f, 1.0f, 1.0f, Curve::Linear, 15.0f, false},
    {3, "mode", 0.0f, 1.0f, 0.0f, Curve::Stepped, 0.0f, false},
};

inline constexpr std::span<const ParamSpec> kMidiFxScale{};  // no parameters

inline constexpr ParamSpec kMidiFxChord[] = {
    {0, "i1", -12.0f, 24.0f, 4.0f, Curve::Stepped, 0.0f, false},
    {1, "i2", -12.0f, 24.0f, 7.0f, Curve::Stepped, 0.0f, false},
    {2, "i3", -12.0f, 24.0f, 0.0f, Curve::Stepped, 0.0f, false},
};

inline constexpr ParamSpec kMidiFxArp[] = {
    {0, "rate", 0.0f, 5.0f, 3.0f, Curve::Stepped, 0.0f, false},
    {1, "mode", 0.0f, 3.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {2, "pat", 0.0f, 3.0f, 0.0f, Curve::Stepped, 0.0f, false},
    {3, "oct", 1.0f, 4.0f, 1.0f, Curve::Stepped, 0.0f, false},
    {4, "gate", 0.1f, 1.0f, 0.8f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kMidiFxVelo[] = {
    {0, "scale", 0.0f, 2.0f, 1.0f, Curve::Linear, 15.0f, false},
    {1, "rand", 0.0f, 1.0f, 0.0f, Curve::Linear, 15.0f, false},
};

inline constexpr ParamSpec kMidiFxRand[] = {
    {0, "chance", 0.0f, 1.0f, 1.0f, Curve::Linear, 15.0f, false},
    {1, "octave", 0.0f, 1.0f, 0.0f, Curve::Linear, 15.0f, false},
};

}  // namespace ddaw::schema
