#!/usr/bin/env python3
"""Generate src/devices/schema/Schema.generated.h from synthyy's param registry.

The Rust registry (crates/sf-project/src/registry.rs, transcribed from the frozen
src/audio/schema.ts) is the single source of truth for parameter keys, ranges, defaults and
curves. This script only reads it. Regenerate after a synthyy schema change:
    python3 tools/a2/gen_schema.py [path/to/registry.rs]
Mapping: int -> Curve::Stepped (no smoothing), exp (min,max > 0) -> Curve::Exponential, else Linear.
A table with a `rateSwitch` knob (Sync/Low/High rate) gets the three extra params schema.ts defines for it,
appended after the existing ones so existing indices never move (schema.ts RATE_*): rateMode (stepped, 0 Sync,
1 Low = the `rate` Hz knob, 2 High = rateHi), rateSync (stepped, index into 8 bar ... 1/16), rateHi (301..1000 Hz).
Cycle length per rateSync index in transport ticks (PPQ 96): 3072, 1536, 768, 384, 192, 96, 48, 32, 24.
"""
import os, re, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/Documents/synthyy/crates/sf-project/src/registry.rs")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../src/devices/schema/Schema.generated.h")

text = open(SRC).read()
table_re = re.compile(r"static (INST|FX|MIDIFX)_([A-Z0-9]+): \[ParamSpec; (\d+)\] = \[(.*?)\n\];", re.S)
spec_re = re.compile(
    r'ParamSpec \{ key: "(?P<key>[^"]+)", label: "(?P<label>[^"]*)", min: (?P<min>[-\d.e+]+), max: (?P<max>[-\d.e+]+), '
    r'def: (?P<def>[-\d.e+]+), curve: Curve::(?P<curve>\w+), int: (?P<int>true|false), steps: (?P<steps>.*?), rate_switch: (?P<rs>true|false) \}')

def num(s):
    s = s.rstrip("0").rstrip(".") if "." in s and "e" not in s else s
    return s if ("." in s or "e" in s) else s + ".0"

out = ['// GENERATED by tools/a2/gen_schema.py from synthyy registry.rs. Do not edit.',
       '#pragma once', '#include "core/Device.h"', '', 'namespace ddaw::schema {', '']
count = 0
names = {"INST": [], "FX": [], "MIDIFX": []}
for kind, name, n, body in table_re.findall(text):
    specs = [m.groupdict() for m in spec_re.finditer(body)]
    assert len(specs) == int(n), f"{kind}_{name}: parsed {len(specs)} of {n}"
    ident = {"INST": "kInst", "FX": "kFx", "MIDIFX": "kMidiFx"}[kind] + name.title().replace("_", "")
    names[kind].append((name.lower(), ident, len(specs)))
    if not specs:
        out.append(f"inline constexpr std::span<const ParamSpec> {ident}{{}};  // no parameters\n")
        continue
    out.append(f"inline constexpr ParamSpec {ident}[] = {{")
    for i, s in enumerate(specs):
        curve = "Curve::Stepped" if s["int"] == "true" else ("Curve::Exponential" if s["curve"] == "Exp" and float(s["min"]) > 0 and float(s["max"]) > 0 else "Curve::Linear")
        smooth = "0.0f" if curve == "Curve::Stepped" else "15.0f"
        note = "  // rateSwitch: Sync/Low/High rate modes" if s["rs"] == "true" else ""
        out.append(f'    {{{i}, "{s["key"]}", {num(s["min"])}f, {num(s["max"])}f, {num(s["def"])}f, {curve}, {smooth}, false}},{note}')
        count += 1
    if any(x["rs"] == "true" for x in specs):
        n0 = len(specs)
        out.append(f'    {{{n0}, "rateMode", 0.0f, 2.0f, 1.0f, Curve::Stepped, 0.0f, false}},  // 0 Sync, 1 Low (rate), 2 High (rateHi)')
        out.append(f'    {{{n0 + 1}, "rateSync", 0.0f, 8.0f, 5.0f, Curve::Stepped, 0.0f, false}},  // tempo division index')
        out.append(f'    {{{n0 + 2}, "rateHi", 301.0f, 1000.0f, 440.0f, Curve::Stepped, 0.0f, false}},  // Hz, High mode')
        count += 3
    out.append("};\n")

out.append("}  // namespace ddaw::schema")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("\n".join(out) + "\n")
print(f"wrote {os.path.normpath(OUT)}: {count} params in {sum(len(v) for v in names.values())} tables")
for k, v in names.items(): print(k, ", ".join(f"{n}={c}" for n, _, c in v))
