# Devices register themselves. Every file under src/devices/{instruments,effects}/ that defines
#     std::unique_ptr<InstrumentDevice> make_<type>()      (or EffectDevice)
# is compiled into ddaw_core and added to a generated registry, so a device task never edits a
# shared build file or registry (ARCH 4). Re-run CMake after adding a device (CONFIGURE_DEPENDS
# picks up new files automatically on the next build).
function(ddaw_generate_device_registry out_var out_file)
    file(GLOB sources CONFIGURE_DEPENDS
        ${CMAKE_SOURCE_DIR}/src/devices/instruments/*.cpp
        ${CMAKE_SOURCE_DIR}/src/devices/effects/*.cpp)
    set(decls "")
    set(inst_cases "")
    set(fx_cases "")
    foreach(f ${sources})
        file(STRINGS ${f} lines REGEX "^std::unique_ptr<(Instrument|Effect)Device> make_[a-z0-9_]+\\(\\)")
        foreach(l ${lines})
            if(l MATCHES "^std::unique_ptr<(Instrument|Effect)Device> make_([a-z0-9_]+)\\(\\)")
                set(kind ${CMAKE_MATCH_1})
                set(type ${CMAKE_MATCH_2})
                string(APPEND decls "std::unique_ptr<${kind}Device> make_${type}();\n")
                if(kind STREQUAL "Instrument")
                    string(APPEND inst_cases "    if (type == \"${type}\") return make_${type}();\n")
                else()
                    string(APPEND fx_cases "    if (type == \"${type}\") return make_${type}();\n")
                endif()
            endif()
        endforeach()
    endforeach()
    file(WRITE ${out_file}.tmp "// GENERATED by cmake/DeviceRegistry.cmake. Do not edit.
#include <memory>
#include <string_view>

#include \"core/Device.h\"

namespace ddaw::devices {
${decls}}  // namespace ddaw::devices

namespace ddaw {
std::unique_ptr<InstrumentDevice> createBuiltinInstrument(std::string_view type) {
    using namespace devices;
${inst_cases}    return nullptr;
}
std::unique_ptr<EffectDevice> createBuiltinEffect(std::string_view type) {
    using namespace devices;
${fx_cases}    return nullptr;
}
}  // namespace ddaw
")
    # only touch the real file when the content changed (keeps incremental builds quiet)
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${out_file}.tmp ${out_file})
    set(${out_var} ${sources} PARENT_SCOPE)
endfunction()
